// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: config.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Pubsub        *PubSub                `protobuf:"bytes,3,opt,name=pubsub,proto3" json:"pubsub,omitempty"`
	Security      *Security              `protobuf:"bytes,4,opt,name=security,proto3" json:"security,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppConfig) Reset() {
	*x = AppConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfig) ProtoMessage() {}

func (x *AppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfig.ProtoReflect.Descriptor instead.
func (*AppConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *AppConfig) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *AppConfig) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppConfig) GetPubsub() *PubSub {
	if x != nil {
		return x.Pubsub
	}
	return nil
}

func (x *AppConfig) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Http                  `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Http {
	if x != nil {
		return x.Http
	}
	return nil
}

type Security struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           *Security_Jwt          `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *Security) GetJwt() *Security_Jwt {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type Http struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Cors          *Http_Cors             `protobuf:"bytes,4,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Http) Reset() {
	*x = Http{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http) ProtoMessage() {}

func (x *Http) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http.ProtoReflect.Descriptor instead.
func (*Http) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *Http) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Http) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *Http) GetCors() *Http_Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Dialect       string                 `protobuf:"bytes,2,opt,name=dialect,proto3" json:"dialect,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Debug         bool                   `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	Pool          *Database_Pool         `protobuf:"bytes,5,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Database) GetDialect() string {
	if x != nil {
		return x.Dialect
	}
	return ""
}

func (x *Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Database) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Database) GetPool() *Database_Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Database              `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Redis                 `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *Data) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type PubSub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kafka         map[string]*Kafka      `protobuf:"bytes,1,rep,name=kafka,proto3" json:"kafka,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSub) Reset() {
	*x = PubSub{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub) ProtoMessage() {}

func (x *PubSub) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub.ProtoReflect.Descriptor instead.
func (*PubSub) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *PubSub) GetKafka() map[string]*Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

type Kafka struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []string               `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Consumer      *Kafka_Consumer        `protobuf:"bytes,3,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Producer      *Kafka_Producer        `protobuf:"bytes,4,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kafka) Reset() {
	*x = Kafka{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka) ProtoMessage() {}

func (x *Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka.ProtoReflect.Descriptor instead.
func (*Kafka) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *Kafka) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *Kafka) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Kafka) GetConsumer() *Kafka_Consumer {
	if x != nil {
		return x.Consumer
	}
	return nil
}

func (x *Kafka) GetProducer() *Kafka_Producer {
	if x != nil {
		return x.Producer
	}
	return nil
}

type Security_Jwt struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Secret                string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	TokenExpirySec        int32                  `protobuf:"varint,2,opt,name=token_expiry_sec,json=tokenExpirySec,proto3" json:"token_expiry_sec,omitempty"`
	RefreshTokenSecret    string                 `protobuf:"bytes,3,opt,name=refresh_token_secret,json=refreshTokenSecret,proto3" json:"refresh_token_secret,omitempty"`
	RefreshTokenExpirySec int32                  `protobuf:"varint,4,opt,name=refresh_token_expiry_sec,json=refreshTokenExpirySec,proto3" json:"refresh_token_expiry_sec,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Security_Jwt) Reset() {
	*x = Security_Jwt{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_Jwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_Jwt) ProtoMessage() {}

func (x *Security_Jwt) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_Jwt.ProtoReflect.Descriptor instead.
func (*Security_Jwt) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Security_Jwt) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Security_Jwt) GetTokenExpirySec() int32 {
	if x != nil {
		return x.TokenExpirySec
	}
	return 0
}

func (x *Security_Jwt) GetRefreshTokenSecret() string {
	if x != nil {
		return x.RefreshTokenSecret
	}
	return ""
}

func (x *Security_Jwt) GetRefreshTokenExpirySec() int32 {
	if x != nil {
		return x.RefreshTokenExpirySec
	}
	return 0
}

type Http_Cors struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllowOrigins     []string               `protobuf:"bytes,1,rep,name=allow_origins,json=allowOrigins,proto3" json:"allow_origins,omitempty"`
	AllowMethods     []string               `protobuf:"bytes,2,rep,name=allow_methods,json=allowMethods,proto3" json:"allow_methods,omitempty"`
	AllowHeaders     []string               `protobuf:"bytes,3,rep,name=allow_headers,json=allowHeaders,proto3" json:"allow_headers,omitempty"`
	ExposeHeaders    []string               `protobuf:"bytes,4,rep,name=expose_headers,json=exposeHeaders,proto3" json:"expose_headers,omitempty"`
	AllowCredentials bool                   `protobuf:"varint,5,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	MaxAge           int32                  `protobuf:"varint,6,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Http_Cors) Reset() {
	*x = Http_Cors{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http_Cors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http_Cors) ProtoMessage() {}

func (x *Http_Cors) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http_Cors.ProtoReflect.Descriptor instead.
func (*Http_Cors) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Http_Cors) GetAllowOrigins() []string {
	if x != nil {
		return x.AllowOrigins
	}
	return nil
}

func (x *Http_Cors) GetAllowMethods() []string {
	if x != nil {
		return x.AllowMethods
	}
	return nil
}

func (x *Http_Cors) GetAllowHeaders() []string {
	if x != nil {
		return x.AllowHeaders
	}
	return nil
}

func (x *Http_Cors) GetExposeHeaders() []string {
	if x != nil {
		return x.ExposeHeaders
	}
	return nil
}

func (x *Http_Cors) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *Http_Cors) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

type Database_Pool struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxIdleConns    int32                  `protobuf:"varint,1,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxOpenConns    int32                  `protobuf:"varint,2,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	ConnMaxLifetime string                 `protobuf:"bytes,3,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	ConnMaxIdleTime string                 `protobuf:"bytes,4,opt,name=conn_max_idle_time,json=connMaxIdleTime,proto3" json:"conn_max_idle_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Database_Pool) Reset() {
	*x = Database_Pool{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database_Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_Pool) ProtoMessage() {}

func (x *Database_Pool) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_Pool.ProtoReflect.Descriptor instead.
func (*Database_Pool) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Database_Pool) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Database_Pool) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Database_Pool) GetConnMaxLifetime() string {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return ""
}

func (x *Database_Pool) GetConnMaxIdleTime() string {
	if x != nil {
		return x.ConnMaxIdleTime
	}
	return ""
}

type Kafka_Consumer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	StartOffset   int32                  `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	Instances     int32                  `protobuf:"varint,3,opt,name=instances,proto3" json:"instances,omitempty"`
	LogMessage    bool                   `protobuf:"varint,4,opt,name=log_message,json=logMessage,proto3" json:"log_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kafka_Consumer) Reset() {
	*x = Kafka_Consumer{}
	mi := &file_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka_Consumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka_Consumer) ProtoMessage() {}

func (x *Kafka_Consumer) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka_Consumer.ProtoReflect.Descriptor instead.
func (*Kafka_Consumer) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Kafka_Consumer) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Kafka_Consumer) GetStartOffset() int32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *Kafka_Consumer) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *Kafka_Consumer) GetLogMessage() bool {
	if x != nil {
		return x.LogMessage
	}
	return false
}

type Kafka_Producer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acks          int32                  `protobuf:"varint,1,opt,name=acks,proto3" json:"acks,omitempty"`
	LogMessage    bool                   `protobuf:"varint,2,opt,name=log_message,json=logMessage,proto3" json:"log_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kafka_Producer) Reset() {
	*x = Kafka_Producer{}
	mi := &file_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka_Producer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka_Producer) ProtoMessage() {}

func (x *Kafka_Producer) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka_Producer.ProtoReflect.Descriptor instead.
func (*Kafka_Producer) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8, 1}
}

func (x *Kafka_Producer) GetAcks() int32 {
	if x != nil {
		return x.Acks
	}
	return 0
}

func (x *Kafka_Producer) GetLogMessage() bool {
	if x != nil {
		return x.LogMessage
	}
	return false
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\vlynx.config\"\xbf\x01\n" +
	"\tAppConfig\x12+\n" +
	"\x06server\x18\x01 \x01(\v2\x13.lynx.config.ServerR\x06server\x12%\n" +
	"\x04data\x18\x02 \x01(\v2\x11.lynx.config.DataR\x04data\x12+\n" +
	"\x06pubsub\x18\x03 \x01(\v2\x13.lynx.config.PubSubR\x06pubsub\x121\n" +
	"\bsecurity\x18\x04 \x01(\v2\x15.lynx.config.SecurityR\bsecurity\"/\n" +
	"\x06Server\x12%\n" +
	"\x04http\x18\x01 \x01(\v2\x11.lynx.config.HttpR\x04http\"\xec\x01\n" +
	"\bSecurity\x12+\n" +
	"\x03jwt\x18\x01 \x01(\v2\x19.lynx.config.Security.JwtR\x03jwt\x1a\xb2\x01\n" +
	"\x03Jwt\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12(\n" +
	"\x10token_expiry_sec\x18\x02 \x01(\x05R\x0etokenExpirySec\x120\n" +
	"\x14refresh_token_secret\x18\x03 \x01(\tR\x12refreshTokenSecret\x127\n" +
	"\x18refresh_token_expiry_sec\x18\x04 \x01(\x05R\x15refreshTokenExpirySec\"\xc5\x02\n" +
	"\x04Http\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\x12*\n" +
	"\x04cors\x18\x04 \x01(\v2\x16.lynx.config.Http.CorsR\x04cors\x1a\xe2\x01\n" +
	"\x04Cors\x12#\n" +
	"\rallow_origins\x18\x01 \x03(\tR\fallowOrigins\x12#\n" +
	"\rallow_methods\x18\x02 \x03(\tR\fallowMethods\x12#\n" +
	"\rallow_headers\x18\x03 \x03(\tR\fallowHeaders\x12%\n" +
	"\x0eexpose_headers\x18\x04 \x03(\tR\rexposeHeaders\x12+\n" +
	"\x11allow_credentials\x18\x05 \x01(\bR\x10allowCredentials\x12\x17\n" +
	"\amax_age\x18\x06 \x01(\x05R\x06maxAge\"\xc8\x02\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x18\n" +
	"\adialect\x18\x02 \x01(\tR\adialect\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05debug\x18\x04 \x01(\bR\x05debug\x12.\n" +
	"\x04pool\x18\x05 \x01(\v2\x1a.lynx.config.Database.PoolR\x04pool\x1a\xab\x01\n" +
	"\x04Pool\x12$\n" +
	"\x0emax_idle_conns\x18\x01 \x01(\x05R\fmaxIdleConns\x12$\n" +
	"\x0emax_open_conns\x18\x02 \x01(\x05R\fmaxOpenConns\x12*\n" +
	"\x11conn_max_lifetime\x18\x03 \x01(\tR\x0fconnMaxLifetime\x12+\n" +
	"\x12conn_max_idle_time\x18\x04 \x01(\tR\x0fconnMaxIdleTime\"G\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\"c\n" +
	"\x04Data\x121\n" +
	"\bdatabase\x18\x01 \x01(\v2\x15.lynx.config.DatabaseR\bdatabase\x12(\n" +
	"\x05redis\x18\x02 \x01(\v2\x12.lynx.config.RedisR\x05redis\"\x8c\x01\n" +
	"\x06PubSub\x124\n" +
	"\x05kafka\x18\x01 \x03(\v2\x1e.lynx.config.PubSub.KafkaEntryR\x05kafka\x1aL\n" +
	"\n" +
	"KafkaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.lynx.config.KafkaR\x05value:\x028\x01\"\xf4\x02\n" +
	"\x05Kafka\x12\x18\n" +
	"\abrokers\x18\x01 \x03(\tR\abrokers\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x127\n" +
	"\bconsumer\x18\x03 \x01(\v2\x1b.lynx.config.Kafka.ConsumerR\bconsumer\x127\n" +
	"\bproducer\x18\x04 \x01(\v2\x1b.lynx.config.Kafka.ProducerR\bproducer\x1a\x87\x01\n" +
	"\bConsumer\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x05R\vstartOffset\x12\x1c\n" +
	"\tinstances\x18\x03 \x01(\x05R\tinstances\x12\x1f\n" +
	"\vlog_message\x18\x04 \x01(\bR\n" +
	"logMessage\x1a?\n" +
	"\bProducer\x12\x12\n" +
	"\x04acks\x18\x01 \x01(\x05R\x04acks\x12\x1f\n" +
	"\vlog_message\x18\x02 \x01(\bR\n" +
	"logMessageBCZAgithub.com/lynx-go/lynx-app-template/internal/pkg/config;configpbb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_config_proto_goTypes = []any{
	(*AppConfig)(nil),      // 0: lynx.config.AppConfig
	(*Server)(nil),         // 1: lynx.config.Server
	(*Security)(nil),       // 2: lynx.config.Security
	(*Http)(nil),           // 3: lynx.config.Http
	(*Database)(nil),       // 4: lynx.config.Database
	(*Redis)(nil),          // 5: lynx.config.Redis
	(*Data)(nil),           // 6: lynx.config.Data
	(*PubSub)(nil),         // 7: lynx.config.PubSub
	(*Kafka)(nil),          // 8: lynx.config.Kafka
	(*Security_Jwt)(nil),   // 9: lynx.config.Security.Jwt
	(*Http_Cors)(nil),      // 10: lynx.config.Http.Cors
	(*Database_Pool)(nil),  // 11: lynx.config.Database.Pool
	nil,                    // 12: lynx.config.PubSub.KafkaEntry
	(*Kafka_Consumer)(nil), // 13: lynx.config.Kafka.Consumer
	(*Kafka_Producer)(nil), // 14: lynx.config.Kafka.Producer
}
var file_config_proto_depIdxs = []int32{
	1,  // 0: lynx.config.AppConfig.server:type_name -> lynx.config.Server
	6,  // 1: lynx.config.AppConfig.data:type_name -> lynx.config.Data
	7,  // 2: lynx.config.AppConfig.pubsub:type_name -> lynx.config.PubSub
	2,  // 3: lynx.config.AppConfig.security:type_name -> lynx.config.Security
	3,  // 4: lynx.config.Server.http:type_name -> lynx.config.Http
	9,  // 5: lynx.config.Security.jwt:type_name -> lynx.config.Security.Jwt
	10, // 6: lynx.config.Http.cors:type_name -> lynx.config.Http.Cors
	11, // 7: lynx.config.Database.pool:type_name -> lynx.config.Database.Pool
	4,  // 8: lynx.config.Data.database:type_name -> lynx.config.Database
	5,  // 9: lynx.config.Data.redis:type_name -> lynx.config.Redis
	12, // 10: lynx.config.PubSub.kafka:type_name -> lynx.config.PubSub.KafkaEntry
	13, // 11: lynx.config.Kafka.consumer:type_name -> lynx.config.Kafka.Consumer
	14, // 12: lynx.config.Kafka.producer:type_name -> lynx.config.Kafka.Producer
	8,  // 13: lynx.config.PubSub.KafkaEntry.value:type_name -> lynx.config.Kafka
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
