// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx-app-template/internal/api/events"
	"github.com/lynx-go/lynx-app-template/internal/api/http"
	"github.com/lynx-go/lynx-app-template/internal/infra/server"
	"github.com/lynx-go/lynx/boot"
	"log/slog"
)

import (
	_ "github.com/jackc/pgx/v5/stdlib"
)

// Injectors from wire.go:

func wireBootstrap(app lynx.Lynx, slogger *slog.Logger) (*boot.Bootstrap, func(), error) {
	pubSub := server.NewPubSub()
	helloHandler := events.NewHelloHandler()
	router := server.NewPubSubRouter(pubSub, helloHandler)
	onStartHooks := NewOnStarts(router)
	onStopHooks := NewOnStops()
	appConfig, err := NewConfig(app)
	if err != nil {
		return nil, nil, err
	}
	helloAPI := http.NewHelloAPI(pubSub)
	echo := server.NewRouter(helloAPI)
	httpServer := server.NewHTTPServer(appConfig, echo)
	scheduler, err := server.NewScheduler()
	if err != nil {
		return nil, nil, err
	}
	binder := server.NewPubSubBinderForServer(pubSub, appConfig)
	v := NewComponents(httpServer, scheduler, pubSub, binder)
	v2 := NewComponentBuilders(binder)
	bootstrap := boot.New(onStartHooks, onStopHooks, v, v2)
	return bootstrap, func() {
	}, nil
}
